### ISSUE TITLE
Comparison with already existing alternatives

### ISSUE THREAD

**Issue by dandv** [smashwilson/typescript-module-template#70]
https://github.com/lukeed/typescript-module would be one

**Comment by smashwilson** [comment]
Sure. I made this repo for my own convenience... if it's useful to someone else, then great, but that's a bonus. I'm not _particularly_ interested in trying to maintain it or market it or anything like that. I'm sure there are many others better equipped to do that!

(I also stopped making new TypeScript modules that would benefit from it almost immediately. C'est la vie...)
